# Generated by Django 2.1.7 on 2020-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200301_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo'),
        ),
    ]
