# Generated by Django 2.2.10 on 2020-03-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
